AgnostiqHQ/covalent

- .github/workflows/publish_develop.yml
- .github/workflows/publish_master.yml
- .github/workflows/pull_request.yml
> Adding a run script for dispatch

- .github/workflows/tests.yml
This PR will freeze the `master` branch.
I am planning to use admin privileges to merge it without updating the version.
> freezing master on 0.32.3

- .github/workflows/release.yml
- .github/workflows/tests.yml
This PR will re-enable the automatic push to `master`
I plan to use admin privileges to merge without updating the version
> unfreeze master

- .github/workflows/changelog.yml
- .github/workflows/tests.yml
- CHANGELOG.md
> single quotes in github env

- .github/workflows/changelog.yml
- .github/workflows/tests.yml
- CHANGELOG.md
> don't use for loops to iterate over variable in bash

- .github/workflows/changelog.yml
- .github/workflows/tests.yml
- CHANGELOG.md
> Fixing issues with checkout actions

- .github/workflows/changelog.yml
- .github/workflows/tests.yml
- CHANGELOG.md
> use covalent ops bot token for automated pushes to develop

- CHANGELOG.md
- covalent_dispatcher/_cli/supervisord.template.conf
- refactor/queuer/app/core/api.py
- refactor/results/app/core/config.py
- refactor/results/main.py
> Integration Supervisord / Queuer / Results Service

- .github/workflows/tests.yml
- CHANGELOG.md
> oneline bugfix to remove fetch --unshallow

- CHANGELOG.md
- covalent_ui/app.py
This creates the sqlite db if it doesn't already exist.
> Instantiate DispatchDB upon server start.

- CHANGELOG.md
- refactor/dispatcher/app/core/dispatch_workflow.py
- refactor/dispatcher/app/core/update_workflow.py
> Update workflow logic updated

- CHANGELOG.md
- covalent/executor/__init__.py
- tests/covalent_tests/executor/init_test.py
> add test for version check

- CHANGELOG.md
- refactor/data/app/core/config.py
- refactor/dispatcher/app/core/get_svc_uri.py
- refactor/dispatcher/app/core/utils.py
> Remove hardcoded filepaths

- CHANGELOG.md
- docker-compose.dev.yml
- docker-compose.yml
> adding nats service

- .github/workflows/pypi.yml
- CHANGELOG.md
> fixing pypi workflow

- .github/workflows/tests.yml
- CHANGELOG.md
> fixing syntax error in tests workflow

- .github/workflows/pypi.yml
- CHANGELOG.md
> pypi uses token

- CHANGELOG.md
- covalent/_shared_files/config.py
> Accessing ENV_DEST_DIR using os.environ.get

- CHANGELOG.md
- requirements.txt
- requirements_sdk.txt
> adding missing requirements

- CHANGELOG.md
- covalent_dispatcher/tests/test_update_workflow.py
> fixing centos runner test

- .detect_secrets_filters/ipynb_hash_filter.py
- .pre-commit-config.yaml
- .secrets.baseline
- CHANGELOG.md
- CONTRIBUTING.md
- covalent_data/Dockerfile
- tests/requirements.txt
Towards #30 
EDIT 1: 
Looks like `detect-secrets` is not present on conda's channels:
https://gist.github.com/m-chaturvedi/44acf521f6c43af0101107bf855dc95e
~Also, removing `turtle` as per #382~
> Add a pre-commit hook for `detect-secrets`

- CHANGELOG.md
- setup.py
> revert exclude in setup.py

- .github/CODEOWNERS
- .secrets.baseline
- CHANGELOG.md
- covalent_data/Dockerfile
> remove incompatible detect-secrets syntax from Dockerfile

- .github/workflows/tests.yml
- CHANGELOG.md
> reusable workflow called at job level

- .github/workflows/tests.yml
- CHANGELOG.md
> Release action fix

- .github/workflows/publish_develop.yml
- .github/workflows/publish_master.yml
- CHANGELOG.md
> Changing hypens to underscores

- CHANGELOG.md
- covalent/_shared_files/config.py
> dotenv hotfix

- CHANGELOG.md
- README.md
> restructured the readme

- .github/workflows/tests.yml
- CHANGELOG.md
> using granular coverage reports

- .github/workflows/badges.yml
- .github/workflows/changelog.yml
- .github/workflows/codeql.yml
- .github/workflows/hotfix.yml
- .github/workflows/publish_develop.yml
- .github/workflows/publish_master.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- CHANGELOG.md
> Disable bot alerts

- CHANGELOG.md
- doc/source/index.rst
> updating video url

- CHANGELOG.md
- tests/stress_tests/scripts/mnist_sublattices.py
- tests/stress_tests/scripts/parallel_cpu.py
- tests/stress_tests/scripts/parallel_cpumem.py
- tests/stress_tests/scripts/parallel_light.py
- tests/stress_tests/scripts/parallel_mem.py
- tests/stress_tests/scripts/parallel_mixed.py
- tests/stress_tests/scripts/postprocess_benchmarks.py
- tests/stress_tests/scripts/serial_light.py
- tests/stress_tests/scripts/squaregraph_light.py
- tests/stress_tests/scripts/sublattices_mixed.py
- tests/stress_tests/scripts/tasks.py
> Add scalability tests

- CHANGELOG.md
- covalent_ui/main.py
> Disabling reloading on UI Backend

- .github/workflows/badges.yml
- .github/workflows/changelog.yml
- .github/workflows/codeql.yml
- .github/workflows/hotfix.yml
- .github/workflows/publish_develop.yml
- .github/workflows/publish_master.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- CHANGELOG.md
> enable CovalentOpsBot

- CHANGELOG.md
- covalent_data/requirements/dist.txt
- requirements.txt
> SQS Docker build Issue

- CHANGELOG.md
- doc/source/tutorials/machine_learning/mnist_classifier.ipynb
> 582 MNIST tutorial typo correction

- CHANGELOG.md
- CONTRIBUTING.md
> add minor updates to contributing guide

- CHANGELOG.md
- covalent_ui/app.py
- [x ] I have updated the documentation and CHANGELOG accordingly.
- [x ] I have read the CONTRIBUTING document.
> Fix Dask daemon worker issue by configuring Dask to disable starting daemonic workers

- .github/workflows/tests.yml
- CHANGELOG.md
> 758 add a retry action to the tests workflow

- .gitignore
- CHANGELOG.md
- covalent/_workflow/electron.py
- tests/workflow_stack_test.py
> tests for electron.py

- CHANGELOG.md
- covalent/_data_store/models.py
- covalent/_results_manager/write_result_to_db.py
- tests/covalent_tests/results_manager_tests/results_test.py
> Update electron dependency tables

- .github/workflows/tests.yml
- CHANGELOG.md
> fixing the retry block

- CHANGELOG.md
- covalent/_workflow/lattice.py
- requirements.txt
- tests/workflow_stack_test.py
> removing matplotlib and draw_inline

- .github/CODEOWNERS
- CHANGELOG.md
> psiog will only own js files

- .github/actions/changelog/dist/index.js
- .github/actions/changelog/index.js
- CHANGELOG.md
> fix in changelog action to handle null author when a bot is committing

- CHANGELOG.md
- covalent/_results_manager/result.py
> Update the result object string dunder method

- CHANGELOG.md
- covalent/_data_store/datastore.py
- tests/covalent_tests/data_store/data_store_test.py
> 891 db migration uri update

- CHANGELOG.md
- covalent/_data_store/datastore.py
- covalent/_results_manager/result.py
- covalent/_results_manager/results_manager.py
- covalent_dispatcher/_core/execution.py
- tests/workflow_stack_test.py
> Add default DB so that client doesnt have to specify it

- CHANGELOG.md
- covalent/__init__.py
- covalent/_workflow/electron.py
- doc/source/concepts/concepts.rst
- tests/covalent_tests/workflow_stack_test.py
> Implement static wait for

- .github/workflows/tests.yml
- .gitignore
- CHANGELOG.md
- codecov.yml
> enabling codecov carryforward

- CHANGELOG.md
- README.md
> Removed migration guide from README

- .github/workflows/tests.yml
- CHANGELOG.md
> Explicitly check release == true in tests.yml

- CHANGELOG.md
- covalent/_data_store/datastore.py
- covalent_dispatcher/_cli/groups/db.py
> Updated CLI to factor in relative path ref of alembic.ini file

- CHANGELOG.md
- tests/covalent_tests/workflow/lattice_serialization_test.py
> Fix randomly failing lattice json serialization test

- CHANGELOG.md
- covalent/_shared_files/logger.py
- covalent_dispatcher/_cli/service.py
- tests/covalent_dispatcher_tests/_cli/service_test.py
- tests/functional_tests/dask_cluster_cli_test.py
> pretty print cluster cli output, fix dask tests

- CHANGELOG.md
- tests/covalent_dispatcher_tests/_cli/service_test.py
> fix set_config call count

- CHANGELOG.md
- covalent/executor/__init__.py
> fix import bug

- .github/workflows/release.yml
- CHANGELOG.md
> update conditions on the pre-release and stable releases

- CHANGELOG.md
- doc/source/how_to/orchestration/construct_lepton.ipynb
- [] I have added the tests to cover my changes.
Closes #551
> Fix how-to for python leptons

- CHANGELOG.md
- doc/source/how_to/orchestration/construct_bash_task.ipynb
> 1031 fix bash lepton howto

- CHANGELOG.md
- doc/source/how_to/index.rst
> Disabling how-to guide on choosing conda environments

- .github/workflows/release.yml
- CHANGELOG.md
> -y flag for conda install

- .github/workflows/tests.yml
- CHANGELOG.md
Addresses the recent bug https://github.com/nodesource/distributions/issues/1290
> centos nodesource fix

- .github/workflows/release.yml
- CHANGELOG.md
> use conda skeleton action for build and upload

- .github/workflows/release.yml
- CHANGELOG.md
related to #1057
related to AgnostiqHQ/conda-skeleton-publish#4
related to AgnostiqHQ/conda-skeleton-publish#5
> adding a wait input for the conda action

- CHANGELOG.md
- covalent/_workflow/transport.py
- tests/covalent_tests/workflow/transport_test.py
> Fixing `__doc__` and `__name__` storage in Transportable Object

- CHANGELOG.md
- covalent_migrations/env.py
> Switched the render_as_batch flag to true in alembic env context

- .github/workflows/tests.yml
- CHANGELOG.md
> cat the log file instead of requiring the server CLI

- .github/workflows/tests.yml
- CHANGELOG.md
> fixed boolean logic issues in tests.yml

- CHANGELOG.md
- covalent_dispatcher/_cli/service.py
- covalent_ui/app.py
> enhancing nocluster start

- .github/workflows/nightly.yml
- CHANGELOG.md
> update path refs to local workflows

- .github/workflows/nightly.yml
- CHANGELOG.md
> fix relase.yml ref

- CHANGELOG.md
- doc/source/tutorials/1_QuantumMachineLearning/quantum_embedding_kernel/source.ipynb
> fixing tutorial notebook rendering

- .github/workflows/hotfix.yml
- .github/workflows/release_candidate.yml
- CHANGELOG.md
> improving prerelease workflows

- .github/workflows/test_matrix.json
- CHANGELOG.md
> updating pr test triggers

- CHANGELOG.md
- covalent/_shared_files/defaults.py
- tests/covalent_tests/shared_files/defaults_test.py
> Fix for default executor value setting

- CHANGELOG.md
- covalent/_results_manager/result.py
> Correctly return stderr in get_node_result

- CHANGELOG.md
- covalent/_file_transfer/strategies/s3_strategy.py
- tests/covalent_tests/file_transfer/strategies/s3_strategy_test.py
> Fix s3 file transfer path

- .github/workflows/changelog.yml
- .github/workflows/nightly.yml
- CHANGELOG.md
> update trigger to hourly, change token to ops bot

- .github/workflows/nightly.yml
- CHANGELOG.md
> fix syntax

- .github/actions/version/action.yml
- CHANGELOG.md
Making these changes in response to this failed run (https://github.com/AgnostiqHQ/covalent/actions/runs/3144819962/jobs/5111659925) where the branch being checked out exists on the forked clone not in core `covalent`
> update checkout version and add repo arg

- .github/workflows/nightly.yml
- CHANGELOG.md
> remove owner/tags var, use ops bot token

- .github/workflows/nightly.yml
- CHANGELOG.md
> fixing credentials

- .github/workflows/nightly.yml
- CHANGELOG.md
> Revert nightly schedule

- .github/actions/version/action.yml
- .github/workflows/version.yml
- CHANGELOG.md
> version comparison fix

- .github/workflows/boilerplate.yml
- CHANGELOG.md
- covalent/_workflow/lattice.py
> Boilerplate fix

- .github/workflows/license.yml
- CHANGELOG.md
> #390 change license.yml to use pip-license-checker action

- CHANGELOG.md
- covalent_migrations/env.py
> Updated import statements in alembic env file to refer to updated location of db classes

- CHANGELOG.md
- covalent/_results_manager/result.py
- tests/covalent_tests/results_manager_tests/results_test.py
> remove get_node_value from Result

- CHANGELOG.md
- covalent_dispatcher/_core/__init__.py
- tests/covalent_dispatcher_tests/entry_point_test.py
> fix imports in entry_point

- CHANGELOG.md
- tests/functional_tests/workflow_stack_test.py
`Result.persist() -> update.persist()`
> Fix remaining failing functional tests from sdk-dispatcher decoupling

- .github/workflows/nightly.yml
- CHANGELOG.md
> Increasing nightly workflow frequency (temp)

- .github/workflows/nightly.yml
- CHANGELOG.md
> Revert increase nightly ci freq

- .github/actions/describe/index.js
- .github/workflows/changelog.yml
- .github/workflows/nightly.yml
- CHANGELOG.md
> fixing syntax in describe action

- .github/actions/describe/dist/index.js
- CHANGELOG.md
> Re-compiled describe action to reflect syntax fix

- CHANGELOG.md
- covalent/_shared_files/defaults.py
- tests/covalent_tests/shared_files/defaults_test.py
> Re-applying default executor fix post config file reunification

- CHANGELOG.md
- covalent_dispatcher/_db/write_result_to_db.py
- tests/functional_tests/local_executor_test.py
> Remove debug statement

- CHANGELOG.md
- doc/source/api/executors/awslambda.rst
> Update AWSLambdaExecutor RTD

- CHANGELOG.md
- covalent/_results_manager/result.py
- tests/covalent_tests/results_manager_tests/results_test.py
Convert None outputs to TransportableObject(None)
Closes #1393.
> Ensure that each node output is a TransportableObject when printing

- .github/workflows/nightly.yml
- CHANGELOG.md
> Reverted nightly schedule back to daily at 4:00am

- CHANGELOG.md
- tests/covalent_tests/file_transfer/strategies/s3_strategy_test.py
> Fix folder transfer unit test bug

- CHANGELOG.md
- doc/source/api/executors/awsplugins.rst
> Updated AWS plugins install instructions

- CHANGELOG.md
- doc/source/api/executors/awsbraket.rst
- doc/source/api/executors/awsplugins.rst
> Docs update aws executors

- .github/workflows/nightly.yml
- CHANGELOG.md
- tests/covalent_tests/executor/executor_plugins/local_test.py
> Updated test_local_wrapper_fn_exception_handling test

- CHANGELOG.md
- doc/source/api/executors/slurm.rst
Update `slurm.rst` for functionality introduced in [PR #41 for the covalent-slurm-plugin](https://github.com/AgnostiqHQ/covalent-slurm-plugin/pull/41). The new text matches the readme therein.
> Update Slurm plugin docs with information for new srun options

- CHANGELOG.md
- covalent/_dispatcher_plugins/local.py
- covalent_dispatcher/_core/execution.py
- covalent_dispatcher/_db/datastore.py
- covalent_dispatcher/_db/update.py
- covalent_dispatcher/_db/upsert.py
- covalent_ui/api/v1/data_layer/summary_dal.py
- covalent_ui/api/v1/database/config/db.py
- requirements.txt
- setup.py
- tests/covalent_tests/file_transfer/strategies/s3_strategy_test.py
- tests/covalent_tests/workflow/__init__.py
> adding db backend enhancements

- CHANGELOG.md
- covalent/_shared_files/defaults.py
- tests/covalent_tests/shared_files/config_test.py
Updating the default paths to `directory` like environment variables to avoid creating re-dundant directories when self-hosting
> fix default directory paths

- CHANGELOG.md
> Remove merge conflict symbols from changelog

- .github/workflows/nightly.yml
- CHANGELOG.md
> Reverted nightly frequency back to once a day

- CHANGELOG.md
- covalent/_workflow/electron.py
- tests/functional_tests/workflow_stack_test.py
Includes fixes for
* postprocessing with collection nodes
* compatibility with stable AWS executor plugins
> QA 0.209.0: Fix collection nodes

- CHANGELOG.md
- covalent_ui/webapp/src/components/dispatch/LatticeDispatchOverview.js
- covalent_ui/webapp/src/components/dispatches/ResultListing.js
> UI crash fix when time is null.

- .github/workflows/release.yml
- CHANGELOG.md
> Updated release workflow to continue if release tag already exists

- CHANGELOG.md
- doc/source/tutorials/5_QPUAccessIBM/requirements.txt
- doc/source/tutorials/5_QPUAccessIBM/source.ipynb
- doc/source/tutorials/tutorials.rst
> Added IBMQ tutorial

- CHANGELOG.md
- covalent_dispatcher/_core/data_manager.py
- tests/covalent_dispatcher_tests/_core/data_manager_test.py
- tests/covalent_tests/workflow/transport_graph_ops_test.py
- tests/functional_tests/workflow_stack_test.py
- Fix redispatch bug and add functional tests to catch this failure in the future.
> Fix redispatch bug

- CHANGELOG.md
- covalent_dispatcher/_core/data_manager.py
- tests/covalent_dispatcher_tests/_core/data_manager_test.py
- tests/functional_tests/workflow_stack_test.py
> Fix redispatch transport graph copying bug

- CHANGELOG.md
- doc/source/tutorials/1_QuantumMachineLearning/pennylane_ensemble_classification/source-jvsc-b1861ceb-413c-44fd-9049-76f027265d183c7f2d69-2f7c-43b9-9202-d5b51c50bb22.ipynb
- doc/source/tutorials/1_QuantumMachineLearning/pennylane_ensemble_classification/source.ipynb
> Fix Pennylane tutorial nb

- .github/workflows/tests.yml
- CHANGELOG.md
> Enabled fail CI if error flag to codecov steps in tests workflow

- .github/workflows/release.yml
- CHANGELOG.md
> Added continue-on-error to conda release job

- CHANGELOG.md
- covalent/_results_manager/results_manager.py
- doc/source/api/cancel.rst
- doc/source/api/index.rst
- doc/source/concepts/basics.md
- doc/source/features/cancel.md
- doc/source/how_to/execution/cancel_dispatch.ipynb
- doc/source/how_to/execution/choosing_conda_environments.ipynb
- doc/source/how_to/index.rst
- doc/source/index.rst
> 1535 add dispatch cancellation rtd

- CHANGELOG.md
- covalent/_results_manager/result.py
- covalent/_shared_files/defaults.py
- covalent/_workflow/electron.py
- covalent/_workflow/lattice.py
- covalent/_workflow/postprocessing.py
- covalent/_workflow/transport.py
- covalent_dispatcher/_core/dispatcher.py
- covalent_dispatcher/_core/runner.py
- covalent_dispatcher/_db/update.py
- covalent_dispatcher/_db/write_result_to_db.py
- tests/covalent_dispatcher_tests/_core/dispatcher_test.py
- tests/covalent_dispatcher_tests/_core/execution_test.py
- tests/covalent_dispatcher_tests/_core/runner_test.py
- tests/covalent_dispatcher_tests/_db/update_test.py
- tests/covalent_dispatcher_tests/_db/write_result_to_db_test.py
- tests/covalent_tests/workflow/electron_metadata_test.py
- tests/covalent_tests/workflow/electron_test.py
- tests/covalent_tests/workflow/postprocessing_test.py
> Implement postprocessing electron

- CHANGELOG.md
- covalent/_workflow/lattice.py
- covalent_dispatcher/_db/update.py
- tests/covalent_dispatcher_tests/_core/dispatcher_test.py
- tests/covalent_dispatcher_tests/_core/execution_test.py
- tests/covalent_dispatcher_tests/_core/runner_test.py
- tests/covalent_dispatcher_tests/_db/update_test.py
- tests/covalent_tests/workflow/electron_test.py
- tests/covalent_tests/workflow/postprocessing_test.py
> Postprocess bug fix

- CHANGELOG.md
- covalent/_dispatcher_plugins/local.py
- covalent/_workflow/lattice.py
- covalent/executor/executor_plugins/timing_plugin.py
- covalent_dispatcher/_core/data_manager.py
- covalent_dispatcher/_core/dispatcher.py
- covalent_dispatcher/_db/load.py
- covalent_dispatcher/_db/update.py
- covalent_dispatcher/_service/app.py
- covalent_dispatcher/entry_point.py
- doc/source/how_to/coding/add_pip_dependencies_to_electron.ipynb
- doc/source/how_to/execution/creating_custom_executors.ipynb
- tests/covalent_dispatcher_tests/_db/load_test.py
- tests/covalent_tests/executor/executor_plugins/timing_plugin_test.py
- tests/functional_tests/docs_how_to_test.py
- tests/functional_tests/workflow_stack_test.py
- tests/requirements.txt
> Fix functional tests

- .github/workflows/nightly.yml
- CHANGELOG.md
> Updating `nightly` frequency

- CHANGELOG.md
- doc/source/tutorials/1_QuantumMachineLearning/pennylane_kernel/requirements.txt
- doc/source/tutorials/1_QuantumMachineLearning/pennylane_kernel/source.ipynb
- doc/source/tutorials/machine_learning/dnn_comparison.ipynb
- doc/source/tutorials/machine_learning/requirements.txt
> Fix tutorial requirements file

- .github/workflows/license.yml
- CHANGELOG.md
- tests/functional_tests/qa_basic_workflow_test.py
- tests/functional_tests/qa_call_deps_retval_test.py
- tests/functional_tests/qa_cpu_stress_test.py
- tests/functional_tests/qa_deps_workflow_test.py
- tests/functional_tests/qa_heterogenous_workflows_test.py
- tests/functional_tests/qa_http_file_transfer_test.py
- tests/functional_tests/qa_sublattice_stress_test.py
- tests/functional_tests/qa_svm_workflow_test.py
- tests/functional_tests/qa_wait_for_file_transfer.py
- tests/requirements.txt
> Moved QA scripts to functional tests

- CHANGELOG.md
- doc/source/getting_started/compatibility.rst
Proposal to address https://github.com/AgnostiqHQ/covalent/issues/1590
I didn't bump the version number; would you like me to do that for minor doc fixes as well?
> Add macOS 13 Ventura to compatibility list

- CHANGELOG.md
- covalent/triggers/base.py
- tests/covalent_tests/triggers/base_test.py
> Fixed redispatch and trigger server address passing in base trigger

- .github/actions/stable-changelog/dist/index.js
- .github/actions/stable-changelog/index.js
- CHANGELOG.md
> Removed outdated "already released" check from stable changelog action

- CHANGELOG.md
- covalent/_dispatcher_plugins/local.py
- tests/covalent_tests/dispatcher_plugins/local_test.py
Fixes https://github.com/AgnostiqHQ/covalent/issues/793
> raise error on dispatching a non-lattice

- CHANGELOG.md
- covalent/_dispatcher_plugins/local.py
- tests/covalent_tests/dispatcher_plugins/local_test.py
Fixes https://github.com/AgnostiqHQ/covalent/issues/1260
> dispatch when covalent server is not available

- CHANGELOG.md
- covalent/_workflow/lattice.py
- covalent_ui/result_webhook.py
- tests/covalent_tests/workflow/lattice_test.py
Closes https://github.com/AgnostiqHQ/covalent/issues/836
> open UI page and print URL with draw()

- CHANGELOG.md
- covalent/_shared_files/config.py
- covalent/_shared_files/utils.py
- covalent/_workflow/lattice.py
- covalent_dispatcher/_cli/service.py
- covalent_ui/result_webhook.py
- tests/covalent_dispatcher_tests/_cli/service_test.py
- tests/covalent_tests/shared_files/config_test.py
- tests/covalent_tests/workflow/lattice_test.py
Fixes https://github.com/AgnostiqHQ/covalent/issues/1430
> defer creation of server specific config entries

- CHANGELOG.md
- doc/source/features/triggers.md
Updated trigger's feature docs
> Updated Trigger's feature doc in RTD

- CHANGELOG.md
- doc/source/features/redispatch.md
- doc/source/index.rst
> Redispatch feature page

- CHANGELOG.md
- doc/source/api/executors/slurm.rst
Closes the docs update in #1615 (the SLURM plugin README was updated to better reflect the installation instructions, which I have now mimicked here).
> Update SLURM plugin docs

- CHANGELOG.md
- covalent/_shared_files/config.py
- covalent_dispatcher/_cli/service.py
- tests/covalent_tests/shared_files/config_test.py
> Fixed db path creation

- CHANGELOG.md
- doc/source/api/executors/gcpbatch.rst
- doc/source/api/executors/index.rst
- doc/source/plugins.rst
> Expose GCP Batch RTD

- CHANGELOG.md
- covalent/_workflow/electron.py
- tests/covalent_tests/workflow/electron_test.py
> Adding `executor` as a property

- CHANGELOG.md
- doc/source/api/executors/gcpbatch.rst
> Fix typo in GCP RTD

- .github/workflows/tests.yml
- CHANGELOG.md
> Fixing Nightly: Activating env now in `tests.yml`

- .github/workflows/nightly.yml
- CHANGELOG.md
> Temporarily changing nightly frequency

- .github/workflows/nightly.yml
- CHANGELOG.md
> Reverted Nightly Frequency

- CHANGELOG.md
- tests/functional_tests/docs_how_to_test.py
> Fix failing gcp howto test

- CHANGELOG.md
- requirements-client.txt
- requirements.txt
> Dask and Distributed version updated

- CHANGELOG.md
- doc/source/getting_started/quick_start/index.rst
Updating the quickstart to include commonly used features.
> updating the quickstart

- CHANGELOG.md
- doc/source/getting_started/quick_start/index.rst
Addresses comment : https://github.com/AgnostiqHQ/covalent/pull/1707#issuecomment-1603060005
> Fixed typo in getting started docs

- CHANGELOG.md
- covalent/_shared_files/config.py
Hopefully fixes #1697. 
I tested it manually on Perlmutter and it seems to work as expected and fixes the hang when importing covalent.
> Fix locking contention for #1697

- CHANGELOG.md
- covalent_ui/api/v1/models/dispatch_model.py
- covalent_ui/api/v1/models/logs_model.py
- covalent_ui/api/v1/routes/end_points/graph_route.py
> UI api fixing

- CHANGELOG.md
- README.md
> updating doc links in readme

- CHANGELOG.md
- tests/covalent_ui_backend_tests/end_points/summary_test.py
> Fixing nightly

- .pre-commit-config.yaml
- CHANGELOG.md
> updating pre-commit packages

- .github/workflows/nightly.yml
- CHANGELOG.md
> Reverted to daily nightly frequency

- CHANGELOG.md
- covalent_dispatcher/_cli/service.py
> Fix for covalent address not showing when covalent starts

- .gitignore
- CHANGELOG.md
- CONTRIBUTING.md
- Fixes issues #1790 and #1791
> Updated contributing steps and gitignore file

- CHANGELOG.md
- tests/functional_tests/docs_how_to_test.py
Skipping the tests temporarily to unblock unrelated merges to develop. Related issue: #1808 .
> Temporarily skipping the sqlite and database trigger functional tests

- CHANGELOG.md
- doc/generate_docs.py
> Better error handling in generate_docs.py

- .github/workflows/nightly.yml
- CHANGELOG.md
> Temporary more frequent nightlies

- CHANGELOG.md
- covalent/__init__.py
- covalent/_shared_files/schemas/electron.py
- covalent/_shared_files/schemas/lattice.py
- covalent/_workflow/transport.py
- requirements-client.txt
> Minor fixes to pydantic models

- CHANGELOG.md
- tests/functional_tests/file_transfer_test.py
> Fixing failing tests

- .github/workflows/man_0_assign_version.yml
- .github/workflows/man_1_push_to_master.yml
- .github/workflows/man_2_create_prerelease.yml
- .github/workflows/nightly-tests.yml
- .github/workflows/tests.yml
- CHANGELOG.md
> Fixing the github workflows

- .github/workflows/nightly-tests.yml
- CHANGELOG.md
> Fixing scheduled nightly

- .github/actions/changelog/index.js
- CHANGELOG.md
> Removing author email from changelog

- .github/workflows/nightly-tests.yml
- CHANGELOG.md
> Further scheduled nightly fixes

- .github/workflows/release.yml
- CHANGELOG.md
This is a TEMPORARY workaround until we get around upgrading the UI dependencies.
Closes ENG-2098
> Allow legacy openssl providers in release pipeline
