AgnostiqHQ/covalent

.github/workflows/tests.yml
I intend to merge this with the red button without updating the version or changelog.
After this is merged I will loosen the branch protection rules for `develop`
=> freezing master on 0.71.0

.github/workflows/tests.yml, CHANGELOG.md, covalent/executor/base.py, requirements.txt, tests/covalent_tests/executor/base_test.py, tests/covalent_tests/workflow/lattice_serialization_test.py
This also introduces a private `_AbstractBaseExecutor` class
containing a few common attributes and methods.
`BaseAsyncExecutor` is logically related to but not derived from
`BaseExecutor` because the core `execute()` methods are invoked
differently.
By not deriving `BaseAsyncExecutor` from `BaseExecutor`, we also
prevent mistakes like the following:
Let `executor` be derived from `BaseAsyncExecutor`.
```python
if isinstance(executor, BaseExecutor):
executor.execute()
else:
await executor.execute()
```
Closes #978
Also addresses the following CI issues: 
Closes #980 (second attempt), 
Closes #984.
=> Make `BaseAsyncExecutor` and `BaseExecutor` siblings

CHANGELOG.md, doc/source/index.rst
=> Fixed RTD downloads badge image to point to covalent rather than cova

CHANGELOG.md, covalent_dispatcher/_cli/service.py, tests/covalent_dispatcher_tests/_cli/service_test.py
Confirm that the endpoints are live before returning from `covalent start`.
=> Delay returning from covalent start until the endpoints are live

CHANGELOG.md, doc/requirements.txt
There seems to be a version conflict when attempting to include the individual executor plugins in the docs requirements (docs pipeline has covalent at a certain version and aws plugins is pinned to 0.177.0 post dev) which is causing large portions of RTD particularly the API section to have missing content. Solution for now is to remove the executors from docs dependencies which shouldn't cause much of a difference in the RTDs as the docs for executors are quite refined without having to include the interface for the executor classes themselves.
Long term solution includes making sure semver versioning ranges for aws plugins module allows for some flexibility.
=> Fixed missing RTD content under API section

CHANGELOG.md, covalent_dispatcher/_cli/service.py, covalent_dispatcher/_db/dispatchdb.py, covalent_ui/app.py, tests/covalent_dispatcher_tests/_cli/service_test.py, tests/covalent_dispatcher_tests/_service/app_test.py
=> Running migrations automatically if none have run in the past

CHANGELOG.md, covalent/_file_transfer/strategies/s3_strategy.py
Boto3 `list_objects` is unreliable when it comes to listing the directories. When directories are created on the console, they are listed, while directories uploaded using boto3 were not returned by `list_objects`. This PR uses pathlib package to reliably create the subdirectory packages that are needed when downloading files from s3.
Also reported this as a probable [bug report](https://github.com/boto/boto3/issues/3340) to boto3.
=> Fix s3 folder download bug

CHANGELOG.md, doc/source/tutorials/5_QPUAccessIBM/source.ipynb
Changed one line to remove hard-coded values, replaced with dummies.
Alternatively, delete the tutorial.
=> Remove reference to iquhack hub/group/project in IBM quantum tutorial (5)

CHANGELOG.md, tests/covalent_dispatcher_tests/_cli/service_test.py
This should hopefully help fix functional tests on CI...
=> mock set_config so as to not set port as 42 in CI

CHANGELOG.md, doc/source/how_to/coding/wait_for_another_electron.ipynb
The document says for task A to wait on task B but the snippet was doing the opposite.
=> Fix waiting order of electrons in docs

CHANGELOG.md, doc/source/api/executors/slurm.rst
Closes #1695. Also opened a PR in the plugin repo here: https://github.com/AgnostiqHQ/covalent-slurm-plugin/pull/72.
- [N/A] I have added the tests to cover my changes.
=> Add missing `,` to Slurm docs

CHANGELOG.md, doc/source/getting_started/first_experiment/index.rst
The warning "Do not stop the Covalent server while you have running workflows. Stopping the server will kill the workflows." was included twice on [this page](https://covalent.readthedocs.io/en/latest/getting_started/first_experiment/index.html). The second instance doesn't seem like the best spot to include it, because it might scare the user into thinking closing their Python console or killing their Jupyter kernel will kill the server.
=> Remove duplicate "stop server" warning in docs

CHANGELOG.md, covalent/_shared_files/defaults.py
This PR fixes a bug related to executor attribute inheritance.  Previously, if an executor class object was assigned to a lattice's executor or workflow_executor, only the string name would be passed to sublattices, leading to errors such as #1733 and https://github.com/AgnostiqHQ/covalent-slurm-plugin/issues/70.  This small change fixes this so that the dictionary of class metadata is also passed to sublattices.
After this fix, the following examples should work:
1. Executor inheritance
```
executor = MyExecutor(param1, param2)
@ct.electron
def task():
return
@ct.electron
@ct.lattice
def sublattice():
return task()
@ct.lattice(executor=executor)
def workflow():
return sublattice()
```
2. Workflow executor inheritance
```
@ct.lattice(workflow_executor=executor)
def workflow():
return …
```
=> fixing executor data inheritance

CHANGELOG.md, tests/functional_tests/workflow_stack_test.py
=> Fixed decorator functional test failing for nightly

CHANGELOG.md, MANIFEST.in, requirements.txt
- [] I have added the tests to cover my changes.
Closes #1765. Essentially, the existing minimum version for Pydantic causes the UI not to render appropriately. Pydantic > 2 is needed now for Covalent. As such, I have set the minimum version to 2.1.1. I chose 2.1.1 intentionally because: a) I tested it and it works; b) FastAPI strictly does not support 2.0.0, 2.0.1, or 2.1.0 so we can't use 2.0 through 2.1.0 anyway.
=> Update `requirements.txt` to update pydantic minimum version and put `py.typed` in `MANIFEST.in`

CHANGELOG.md, covalent/_shared_files/qelectron_utils.py, covalent_ui/api/v1/data_layer/electron_dal.py
The main issue here is that `Database()` by default points to data inside `~/.local/share/covalent/qelectron_db`. This folder belongs to the QServer.
We should instead use the transferred data in `~/.local/share/covalent/data/<dispatch_id>`, **because the former will NOT exist if the QElectron-containing electron is executed non-locally.**
**Solution:**
With the changes here, we still use the `Database` class to interface with the `.mdb` files. However, we don't have a *single* instance (no more `self.qdb`) that accesses an *single* directory (by default the undesired `~/.local/share/covalent/qelectron_db`).
Instead we specify the directory (i.e. `~/.local/share/covalent/data/<dispatch_id>/...`) every time we need to access *a* (one of arbitrarily many) QElectron database in the Covalent …
=> Modify `Electrons` to use Covalent server's QElectron DBs, instead of QServer QElectron DB

CHANGELOG.md, covalent/executor/executor_plugins/remote_executor.py
Issue - #1785 
Added covalent version attribute to remote_executor.py
=> Fix: #1785 Added covalent version attribute to Remote Executors

CHANGELOG.md, covalent/_workflow/electron.py, covalent/_workflow/postprocessing.py, tests/covalent_tests/workflow/electron_test.py, tests/covalent_tests/workflow/postprocessing_test.py, tests/functional_tests/workflow_stack_test.py
Also use `workflow_executor` to build sublattice graphs
Closes #1781 .
=> Fix propagation of lattice-default attributes to electrons

CHANGELOG.md, covalent/_workflow/lepton.py, requirements.txt, tests/covalent_tests/workflow/lepton_test.py, tests/functional_tests/lepton_test.py
There are some cases where the remote environment lacks `/bin/bash`, but may have `/bin/sh` instead.
inside `exec.py`:
```
...
FileNotFoundError: [Errno 2] No such file or directory: '/bin/bash'
```
This PR has some quick changes to make bash lapton execution check for `bash`, then fall back to `sh`, and finally error out if no shell executable is found.
=> Fallback to `sh` in remote environment if `bash` not available

CHANGELOG.md, tests/covalent_dispatcher_tests/_cli/cli_test.py
Quick fix for this error:
```
ModuleNotFoundError: No module named 'doc/source/how_to/execution/custom_executors/timing_plugin'
```
This happens during `test_deploy_status()` in the CI tests. The reason is that the "timing plugin" created in our how-to's is discovered by `_executor_manager`.
=> Patch executor manager to ignore extra plugins discovered during CI tests

CHANGELOG.md, tests/requirements.txt
There is a boto3 requirement in requirements.txt and in tests/requirements.txt. This will eventually lead to some confusion because it's prone to get out of sync. It is a core dependency, so I kept it in requirements.txt.
=> Remove duplicate `boto3` requirement

CHANGELOG.md, covalent_dispatcher/_cli/groups/deploy_group.py, tests/covalent_dispatcher_tests/_cli/cli_test.py
=> Fixed deploy command failure

CHANGELOG.md, covalent/cloud_resource_manager/core.py
=> Fixed infra defaults for deploy commands

CHANGELOG.md, covalent/cloud_resource_manager/core.py, tests/covalent_tests/cloud_resource_manager/core_test.py
Fix for https://github.com/AgnostiqHQ/covalent/issues/1920
=> Allow non-string infra defaults for plugins

CHANGELOG.md
This PR is to remove my email from the `CHANGELOG` and to replace it with my GitHub username.
When searching for my email via Google, the [only hit](https://www.google.com/search?q=%22asrosen93%40gmail.com%22) is for the Covalent `CHANGELOG`. I've been getting a lot of spam in the last several days, so I would like to clean up this public trace of my email just in case. I have replaced my email with my GitHub username.
By default, it may be worth considering using usernames by default in the `CHANGELOG`. In any case, I'm aware that this is an automated process so this PR is only a band-aid solution. I wasn't sure where to adjust the automated procedure. Also, this PR will obviously fail for updating the `CHANGELOG`.
=> Removing my email from the CHANGELOG

.github/workflows/tests.yml, CHANGELOG.md, covalent/_workflow/electron.py, covalent_dispatcher/_core/dispatcher.py, covalent_dispatcher/_dal/importers/result.py, covalent_dispatcher/_dal/importers/tg.py, tests/covalent_dispatcher_tests/_core/dispatcher_db_integration_test.py, tests/covalent_dispatcher_tests/_core/execution_test.py, tests/covalent_dispatcher_tests/_dal/importers/result_import_test.py, tests/covalent_tests/workflow/electron_test.py, tests/functional_tests/workflow_stack_test.py
The collector electron now assembles the dictionary from two lists -- one list of keys, one list of corresponding values.
Closes #1937 .
=> Do not require dictionary keys to be `str`

CHANGELOG.md, covalent/__init__.py
Moving the suppression of import error to try to deal with other errors until we update PennyLane for qelectron. This solves the conflict of importing covalent prerelease with the latest PennyLane, barring which you get stuck.
```python
AttributeError: type object 'DefaultQubit' has no attribute 'operations'
```
=> Making qelectron import within try except.

.github/workflows/test_matrix.json, .github/workflows/tests.yml, CHANGELOG.md, doc/source/getting_started/compatibility.rst
Update test matrix:
- Add Python 3.11
- Add Debian 12
- Remove Python 3.8
- Remove CentOS 7
- Remove Ubuntu (Debian is close enough)
=> Update recommended platform to Debian 12 / Python 3.10

.github/workflows/test_matrix.json, .github/workflows/tests.yml, CHANGELOG.md, tests/covalent_dispatcher_tests/_cli/service_test.py
=> Fix tests breaking on macos

CHANGELOG.md, covalent/_shared_files/defaults.py, covalent/_workflow/electron.py, covalent/_workflow/lattice.py, tests/covalent_tests/workflow/electron_metadata_test.py, tests/covalent_tests/workflow/lattice_test.py
This should eliminate the need to set workflow_executor explicitly in many cases.
=> Default workflow_executor to lattice-default executor
